Eloquent/oneToMany/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.app');
});

Route::resource('category', 'CategoryController');
Route::resource('product', 'ProductController');

Eloquent/oneToMany/app/Category.php
<?php

namespace App;

use App\Product;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

Eloquent/oneToMany/app/Product.php
<?php

namespace App;

use App\Category;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    public function category()
        {
            return $this->belongsTo(Category::class);
        } 
}

Eloquent/oneToMany/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            Category::create($request->all());
            return redirect()->route('category.index');

        } catch (QueryException $e) {

            return redirect()->back();
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index');
    }
}

Eloquent/oneToMany/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Eloquent/oneToMany/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::all();
        return view('product.index', compact('products'));
    }

    public function create()
    {
        
        $categories = Category::pluck('title','id')->toArray();
        return view('product.create', compact('categories'));
    }

    public function store(Request $request)
    {    
        $data = $request->all();
        $products = Product::create($data);
        return redirect()->route('product.index');     
    }

    public function show($id)
    {
        $products = Product::findOrFail($id);
        $categories = Category::pluck('title','id');
        return view('product.show',compact('products','categories'));
    }

    public function edit($id)
    {
        $product = Product::findOrfail($id);
        $categories = Category::pluck('title','id');
        return view('product.edit',compact('product','categories'));
    }

    public function update(Request $request, Product $product)
    {
        $data = $request->all();
        // dd($data);
        $product->update($data);
        return redirect()->route('product.index');
    }

    public function destroy($id)
    {
        $product = Product::findOrfail($id)->delete();
        
        return redirect()->route('product.index');
    }
}

Eloquent/oneToMany/resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h4>Create Product</h4><br><br>
    <a href="{{ route('product.index') }}" class="btn btn-primary">Back</a>

    {!! Form::open
    (['route' => 'product.store',
    'method' => 'POST'])
    !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title','', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('category_id','Category :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            <select class="custom-select" id="inputGroupSelect01" name="category_id">
                <option selected>Choose One Category ...</option>
                @foreach ($categories as $key => $category)
                <option value="{{ $key }}">{{ $category }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('description','Description :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::textarea('description','', ['class'=>'form-control' ,'rows'=>'3']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('prize','Prize :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('prize','', ['class'=>'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

Eloquent/oneToMany/resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h4>Edit Product</h4><br><br>
    <a href="{{ route('product.index') }}" class="btn btn-primary">Back</a>

    {!! Form::model($product, 
    [
        'route' => ['product.update',$product->id],
        'method' => 'PUT',
    ]) !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title',null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('category_id','Category :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            <select class="custom-select" id="inputGroupSelect01" name="category_id">
                <option selected>{{$product->category->title}}</option>
                @foreach ($categories as $key => $category)
                <option value="{{ $key }}">{{ $category }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('description','Description :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('description',null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group row">
        {!! Form::label('prize','Prize :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('prize',null, ['class' => 'form-control']) !!}
        </div>
    </div>


    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

Eloquent/oneToMany/resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <br><h3>Product List</h3>
    <a href="{{ route('product.create') }}" class="btn btn-success">Create Product</a>

    <table class="table table-hover mt-1">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Prize</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $sl = 1 ?>
            @foreach ($products as $product)
            <tr>
            <th scope="row">{{ $sl++ }}</th>
                <td>{{$product->title}}</td>
                <td>{{ $product->category->title }}</td>
                <td>{{ $product->description}}</td>
                <td>{{ $product->prize}}</td>
                <td class="row">
                    <a href="{{ route('product.show', $product->id) }}" class="btn btn-primary">Show</a>
                    <a href="{{ route('product.edit',$product->id) }}" class="btn btn-success">Edit</a>
                    <form action="{{ route('product.destroy',$product->id) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

Eloquent/oneToMany/resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <br>
    <h3>Product List</h3>
    <a href="{{ route('product.index') }}" class="btn btn-success mb-2">Back To Product List</a>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">title</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Prize</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{$products->title}}</td>
                <td>{{ $products->category->title }}</td>
                <td>{{ $products->description}}</td>
                <td>{{ $products->prize}}</td>
            </tr>

        </tbody>
    </table>
</div>
@endsection