form_crud/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'StudentController@index');

Route::resource('hobby', 'HobbyController');
Route::resource('student', 'StudentController');



// Route::get('/upload', 'UploadFileController@showUpload')->name('student.upload');
// Route::post('/upload', 'UploadFileController@showUploadFile')->name('upload');

form_crud/app/Hobby.php
<?php

namespace App;

use App\Student;
use Illuminate\Database\Eloquent\Model;

class Hobby extends Model
{
    protected $fillable = ['name'];

    public function students(){
        
        return $this->belongsToMany(Student::class);
    }
}

form_crud/app/Picture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Picture extends Model
{
    protected $fillable = ['multipic'];
    
    public function student()
    {
        return $this->belongsTo(Student::class);
    }
}

form_crud/app/Student.php
<?php

namespace App;

use App\Hobby;
use App\Picture;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name','birth','gender','email','tel','color','country','about','image'
    ];

    public function hobbies()
    {
        return $this->belongsToMany(Hobby::class);
    }

    public function pictures()
    {
        return $this->hasMany(Picture::class);
    }
}

form_crud/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

form_crud/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

form_crud/app/Http/Controllers/HobbyController.php
<?php

namespace App\Http\Controllers;

use App\Hobby;
use Illuminate\Http\Request;

class HobbyController extends Controller
{
    public function index(){
        $datas = Hobby::all();
        return view('hobby.index', compact('datas'));
    }
    public function create(){
        return view('hobby.create');
    }
    public function store(Request $request){
        Hobby::create($request->all());
        return redirect()->route('hobby.index');
    }
    public function edit($id){
        $hobby = Hobby::findOrFail($id);
        return view('hobby.edit', compact('hobby'));
    }
    public function update(Request $request, Hobby $hobby){
        $hobby->update($request->all());
        return redirect()->route('hobby.index');
    }
    public function destroy($id){
        Hobby::find($id)
        ->delete();
        return redirect()->route('hobby.index');
    }
}

form_crud/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Image;
use App\Hobby;
use App\Picture;
use App\Student;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;

class StudentController extends Controller
{
    public function index()
    {
     
     $datas = Student::all();
     return view('student.index', compact('datas'));
    }

    public function create()
    {
        $hobbies = Hobby::pluck('name','id')->toArray();
        $images = Picture::pluck('multipic','id')->toArray();
        $data = [];
        return view('student.create', compact('hobbies', 'data','images'));
    }

    public function store(Request $request)
    {
        try {
            // dd($request->multipic);
            $hobby = $request['hobby'];
            $data = $request->all();

            // siglepicture
            if ($request->hasFile('image'))
            {
                $data['image'] = $this->uploadImage($request->image, $request->title);
            }

            $student = Student::create($data);
            $student->hobbies()->attach($hobby);

            // multipicture
            if($request->hasFile('multipic')){
                foreach ($request->multipic as $pic){
                    $student->pictures()->create([
                    'multipic' => $this->uploadMultipleImage($pic),
               ]);
            }
        }
        return redirect()->route('student.index');
            } 
            catch (QueryException $e) {
                return view('student.create');
            }  
    }

    public function show(Student $student)
    {
        return view('student.show', compact('student'));   
    }

    public function edit(Student $student)
    {
        $hobbies = Hobby::pluck('name','id')->toArray();
        $data = $student->hobbies->pluck('id')->toArray();
        return view('student.edit', compact('student', 'hobbies','data'));
    }
    public function update(Request $request, Student $student)
    {
        $data = $request->all();
        if ($request->hasFile('image')) {
            $this->unlink($student->image);
            $data['image'] = $this->uploadImage($request->image, $request->title);
        }
        // multipicture
        if($request->hasFile('multipic')){
            foreach ($request->multipic as $pic){
                $student->pictures()->create([
                'multipic' => $this->uploadMultipleImage($pic),
                ]);
            }
        }
        $student->update($data);
        $hobby = $request->hobby;
        $student->hobbies()->sync($hobby);
        return redirect()->route('student.index');
    }

    public function destroy(Student $student)
    {
        $student->hobbies()->detach();
        $student->delete();
        return redirect()->back();
    }


    private function uploadImage($file, $name)
    {
        $timestamp = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());
        $file_name = $timestamp .'-'.$name. '.' . $file->getClientOriginalExtension();
        $pathToUpload = storage_path().'/app/public/students/';
        Image::make($file)->resize(634,792)->save($pathToUpload.$file_name);
        return $file_name;
    }

    private function unlink($file)
    {
        $pathToUpload = storage_path().'/app/public/students/';
        if ($file != '' && file_exists($pathToUpload. $file)) {
            @unlink($pathToUpload. $file);
        }
    }
// multiple images

private function uploadMultipleImage($file)
{
    $timestamp = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());
    $name = $file->getClientOriginalName();
    $file_name = $timestamp .'-' . $name;
    $pathToUpload = storage_path().'/app/public/students/';
    Image::make($file)->resize(634,792)->save($pathToUpload.$file_name);
    return $file_name;
}
    
   
}

form_crud/app/Http/Controllers/UploadFileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UploadFileController extends Controller
{
    
}

form_crud/resources/views/student/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card mt-5">
        <div class="container">
            <h2>Students Register Form</h2>
            <a href="{{ route('student.index') }}" class="btn btn-success">List</a>
            <hr>
            {!! Form::open([
            'route' => 'student.store',
            'method' => 'POST',
            'enctype' => 'multipart/form-data',
            ]) !!}
            @include('student.form')
            {!! Form::submit('submit', ['class' => 'btn btn-primary mb-1']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

form_crud/resources/views/student/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="card text-left">
      <div class="container">
          <a href="{{ route('student.index') }}" class="btn btn-success">List</a>
          {!! Form::model($student, [
              'route' => ['student.update',$student->id],
              'method' => 'PUT',
              'files' => true
          ]) !!}
          @include('student.form')
          {!! Form::submit('submit' ,['class' => 'btn btn-success ']) !!}
          {!! Form::close() !!}
      </div>
    </div>
@endsection

form_crud/resources/views/student/form.blade.php
<div class="form-group row">
    {!! Form::label('name', 'Student Name :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('birth', 'Birthday (date and time) :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::date('birth', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('gender', 'Gender :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::radio('gender', 'male', false, ['male' => 'Male']) !!}
        {!! Form::label('male', null, []) !!}
        {!! Form::radio('gender', 'female', false, ['female' => 'Female']) !!}
        {!! Form::label('female', null, []) !!}
        {!! Form::radio('gender', 'other', false, ['others' => 'Others']) !!}
        {!! Form::label('others', null, []) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('email', 'E-mail :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::email('email', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('tel', 'Tel-phone :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::tel('tel', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('color', 'Your Favourite Color :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::color('color', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('country', 'Select Country :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::select('country', ['bangladseh' => 'Bangladseh', 'india' => 'India', 'pakistan' => 'pakistan'], null,
        ['class' => 'form-control']) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('hobby', 'Hobbies :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        @foreach ($hobbies as $key=>$hobby)
            {!! Form::checkbox('hobby[]', $key, in_array($key,$data)) !!} {{ $hobby }}
        @endforeach
    </div>
</div>
<div class="form-group row">
    {!! Form::label('about', 'About Yourself :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::textarea('about', null, ['class' => 'form-control', 'rows' => '4']) !!}
    </div>
</div>
{{-- image --}}
<div class="form-group row">
    {!! Form::label('image', 'Picture :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::file('image', null, ['class'=>'col-sm-8']) !!}
    </div>
</div>
{{-- multiple image --}}
<div class="form-group row">
    {!! Form::label('multipic[]', 'Multiple Picture :', null, ['class' => 'col-sm-4']) !!}
    <div class="col-sm-8">
        <input type="file" name="multipic[]" class="col-sm-8" multiple>
    </div>
</div>

form_crud/resources/views/student/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card text-left mt-5">
        <div class="container">
            <h3>Student Information</h3>
            <a href="{{ route('student.create') }}" class="btn btn-success mb-2">Create</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Birthday</th>
                        <th>Tel-phone</th>
                        <th>Country</th>
                        <th>Picture</th>
                        <th>Hobby</th>
                        <th >Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $sl = 1 ?> 
                    @foreach ($datas as $data)
                        <tr>
                            <td>{{ $sl++ }}</td>
                            <td>{{ $data->name }}</td>
                            <td>{{ $data->email }}</td>
                            <td>{{ $data->birth }}</td>
                            <td>{{ $data->tel }}</td>
                            <td>{{ $data->country }}</td>
                            <td>
                                @if(file_exists(storage_path().'/app/public/students/'.$data->image ) && (!is_null($data->image)))
                                    <img src="{{ asset('storage/students/'.$data->image) }}" height="100">
                                @else
                                    {{-- <img src="{{ asset('/default-avatar.png') }}" --}}
                                    No Photo
                            @endif
                            </td>
                            <td>
                                <ul>
                                    @foreach ($data->hobbies as $hobby)
                                        <li>{{ $hobby->name }}</li>
                                    @endforeach
                                </ul>
                            </td>
                            <td>
                                <a href="{{ route('student.show',$data->id) }}" class="btn btn-primary">show</a>
                                <a href="{{ route('student.edit',$data->id) }}" class="btn btn-warning">edit</a>
                                <form action="{{ route('student.destroy', $data->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are You Sure To Delete?')">delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

form_crud/resources/views/student/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card text-left mt-5">
        <div class="container">
            <h3><strong>{{ $student->name }}</strong> Information</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Name</th>
                        <td>{{ $student->name }}</td>
                    </tr>
                    <tr>
                        <th>Birthday</th>
                        <td>{{ $student->birth }}</td>
                    </tr>
                    <tr>
                        <th>E-mail</th>
                        <td>{{ $student->email }}</td>
                    </tr>
                    <tr>
                        <th>Tel Phone</th>
                        <td>{{ $student->tel }}</td>
                    </tr>
                    <tr>
                        <th>Country</th>
                        <td>{{ $student->country }}</td>
                    </tr>
                    <tr>
                        <th>Colour</th>
                        <td>{{ $student->color }}</td>
                    </tr>
                    <tr>
                        <th>About</th>
                        <td>{{ $student->about }}</td>
                    </tr>
                    <tr>
                        <th>Hobbies</th>
                        <td>
                            @if (isset($student->hobbies))
                                <ul>
                                    @foreach ($student->hobbies as $hobby)
                                        <li>{{ $hobby->name }}</li>
                                    @endforeach
                                </ul>
                            @else
                                <div class="alert alert-info" role="alert">
                                    found no hobby
                                </div>
                            @endif

                        </td>
                    </tr>
                    <tr>
                        <th>Picture</th>
                        <td>
                            @if (file_exists(storage_path() . '/app/public/students/' . $student->image) && !is_null($student->image))
                                <img src="{{ asset('storage/students/' . $student->image) }}" height="100">
                            @else
                                {{-- <img src="{{ asset('/default-avatar.png') }}"
                                    --}} No Photo @endif
                        </td>
                    </tr>
                    <tr>
                        <th>Multiple Picture</th>
                        <td>
                            @if (isset($student->pictures))
                                <ul>
                                    @foreach ($student->pictures as $item)
                                        @if (file_exists(storage_path() . '/app/public/students/' . $item->multipic) && !is_null($item->multipic))
                                            <img src="{{ asset('storage/students/' . $item->multipic) }}" height="100">
                                        @endif
                                    @endforeach
                                </ul>
                            @else
                                <div class="alert alert-info" role="alert">
                                    Found no Picture
                                </div>
                            @endif

                        </td>
                    </tr>

                </tbody>
            </table>

            <a href="{{ route('student.index') }}" class="btn btn-success mb-2">Student List</a>
        </div>
    </div>
@endsection

form_crud/resources/views/student/upload.blade.php
@extends('layouts.app')

@push('css')
    <link href="https://transloadit.edgly.net/releases/uppy/v1.20.1/uppy.min.css" rel="stylesheet">

@endpush
@section('content')
        <div id="drag-drop-area" name="mutlipic[]"></div>
@endsection



@push('js')
    <script src="https://transloadit.edgly.net/releases/uppy/v1.20.1/uppy.min.js"></script>
    <script>
        var uppy = Uppy.Core();
        //  uppy.use(Uppy.DragDrop, { target: '.UppyDragDrop' });
        uppy.use(Uppy.Dashboard, {
            inline: true,
            target: '#drag-drop-area'
         })
         uppy.use(Uppy.XHRUpload,
         { 
               endpoint:'http://localhost:8000/student/upload', method:'post'});
               uppy.run(); 
               uppy.on('upload-success', function (fileId, data) {
               console.log("Uploaded!");
           });



        // var uppy = Uppy.Core()
        //     .use(Uppy.Dashboard, {
        //         inline: true,
        //         target: '#drag-drop-area'
        //     })
        //     .use(Uppy.Tus, {
        //         endpoint: 'https://master.tus.io/files/'
        //     }) //you can put upload URL here, where you want to upload images

        // uppy.on('complete', (result) => {
        //     console.log('Upload complete! We’ve uploaded these files:', result.successful)
        // })
        // uppy.on('complete', (result) => {
        //     console.log('Upload complete! We’ve uploaded these files:', result.successful)
        // })



        //         var Uppy = require('uppy/lib/core')
        // var Dashboard = require('uppy/lib/plugins/Dashboard')
        // var XHRUpload = require('uppy/lib/plugins/XHRUpload')
        //         // app.js
        //         uppy.use(XHRUpload, {
        //             endpoint: '',
        //             fieldName: 'my_file'
        //         })
    </script>
@endpush